
name: Build and push image

on:
  push:
    branches:
      - 'main'

jobs:
  testing: 
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout code
        uses: actions/checkout@main

      - name: SonarQube Scan
        uses: hectorgf909/sonarqube-action-1@master
        with:
          host: "http://sonarqube.isban.gs.corp/"
          login: "37c776a76dfad27a6324e782a73fb90ce1a734eb"
          projectBaseDir: "./api"
          projectKey: "gsc:gsc:sdablkaml:aml-backend"
