
name: Build and push image

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  testing: 
    runs-on: sdid1weugvml001
    steps:
  
      - name: Checkout code
        uses: actions/checkout@main

