
name: Build and push image

on:
  push:
    branches:
      - 'main'

jobs:
  testing: 
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout code
        uses: actions/checkout@main

      - name: SonarQube Scan
        working-directory: ./${{ github.event.inputs.path }}
        uses: hectorgf909/sonarqube-action@main
        with:
          host: "test"
          login: "test"
          projectBaseDir: "./api"
          projectKey: "gsc:gsc:sdablkaml:aml-backend"
        