
name: Build and push image

on:
  push:
    branches:
      - 'main'

jobs:
  testing: 
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout code
        uses: actions/checkout@main

      - name: SonarQube Scan
        uses: hectorgf909/sonarqube-action-1@main
        # with:
        #   host: "test"
        #   login: "test"
        #   projectBaseDir: "./api"
        #   projectKey: "gsc:gsc:sdablkaml:aml-backend"
